/*
 * Custody Services
 *
 * This API is part of the OpenWealth APIs for the connectivity between custody banks and WealthTechs (e.g. Portfolio Management Systems). This API allows the user to receive data from custody banks regarding accounts and positions. The API is designed to be used for either update end of day data batches or single near-realtime account/position information. Furthermore, this API allows the user to receive data from custody banks regarding transactions. In this version (2.0) only transactions which include effective cash or securities movements are in scope and corporate actions without any cash impact are delivered only on a informative basis. 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: openwealth@synpulse.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using OpenWealth.Converters;

namespace OpenWealth.Models
{
    /// <summary>
    /// Interest method of the instrument.
    /// </summary>
    /// <value>Interest method of the instrument.</value>

    public enum DayCountBasis
    {

        /// <summary>
        /// Enum Act360 for act_360
        /// </summary>
        [EnumMember(Value = "act_360")]
        Act360 = 1,

        /// <summary>
        /// Enum Act365 for act_365
        /// </summary>
        [EnumMember(Value = "act_365")]
        Act365 = 2,

        /// <summary>
        /// Enum ActActIcma for act_actIcma
        /// </summary>
        [EnumMember(Value = "act_actIcma")]
        ActActIcma = 3,

        /// <summary>
        /// Enum ActActIsda for act_actIsda
        /// </summary>
        [EnumMember(Value = "act_actIsda")]
        ActActIsda = 4,

        /// <summary>
        /// Enum ActActAfb for act_actAfb
        /// </summary>
        [EnumMember(Value = "act_actAfb")]
        ActActAfb = 5,

        /// <summary>
        /// Enum Act365L for act_365L
        /// </summary>
        [EnumMember(Value = "act_365L")]
        Act365L = 6,

        /// <summary>
        /// Enum Bus252 for bus_252
        /// </summary>
        [EnumMember(Value = "bus_252")]
        Bus252 = 7,

        /// <summary>
        /// Enum U30360 for u30_360
        /// </summary>
        [EnumMember(Value = "u30_360")]
        U30360 = 8,

        /// <summary>
        /// Enum U30E360Icma for u30E_360Icma
        /// </summary>
        [EnumMember(Value = "u30E_360Icma")]
        U30E360Icma = 9,

        /// <summary>
        /// Enum U30E360Isda for u30E_360Isda
        /// </summary>
        [EnumMember(Value = "u30E_360Isda")]
        U30E360Isda = 10,

        /// <summary>
        /// Enum U30E360 for u30E_360
        /// </summary>
        [EnumMember(Value = "u30E_360")]
        U30E360 = 11,

        /// <summary>
        /// Enum U30U360 for u30U_360
        /// </summary>
        [EnumMember(Value = "u30U_360")]
        U30U360 = 12
    }
}
