/*
 * Custody Services
 *
 * This API is part of the OpenWealth APIs for the connectivity between custody banks and WealthTechs (e.g. Portfolio Management Systems). This API allows the user to receive data from custody banks regarding accounts and positions. The API is designed to be used for either update end of day data batches or single near-realtime account/position information. Furthermore, this API allows the user to receive data from custody banks regarding transactions. In this version (2.0) only transactions which include effective cash or securities movements are in scope and corporate actions without any cash impact are delivered only on a informative basis. 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: openwealth@synpulse.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using JsonSubTypes;
using OpenWealth.Converters;

namespace OpenWealth.Models
{ 
    /// <summary>
    /// Financial instrument entity.
    /// </summary>
    [DataContract]
    [JsonSubtypes.KnownSubType(typeof(Bond), "bond")]
    [JsonSubtypes.KnownSubType(typeof(MoneyMarket), "callableDeposit")]
    [JsonSubtypes.KnownSubType(typeof(MoneyMarket), "callableLoan")]
    [JsonSubtypes.KnownSubType(typeof(Cash), "cash")]
    [JsonSubtypes.KnownSubType(typeof(Commodity), "commodity")]
    [JsonSubtypes.KnownSubType(typeof(Credit), "credit")]
    [JsonSubtypes.KnownSubType(typeof(CreditDefaultSwap), "creditDefaultSwap")]
    [JsonSubtypes.KnownSubType(typeof(CryptoAsset), "cryptoAsset")]
    [JsonSubtypes.KnownSubType(typeof(Equity), "equity")]
    [JsonSubtypes.KnownSubType(typeof(MoneyMarket), "fixedDeposit")]
    [JsonSubtypes.KnownSubType(typeof(MoneyMarket), "fixedLoan")]
    [JsonSubtypes.KnownSubType(typeof(Fund), "fund")]
    [JsonSubtypes.KnownSubType(typeof(Future), "future")]
    [JsonSubtypes.KnownSubType(typeof(FxForward), "fxForward")]
    [JsonSubtypes.KnownSubType(typeof(FxOption), "fxOption")]
    [JsonSubtypes.KnownSubType(typeof(FxSwap), "fxSwap")]
    [JsonSubtypes.KnownSubType(typeof(Index), "index")]
    [JsonSubtypes.KnownSubType(typeof(InterestRateSwap), "interestRateSwap")]
    [JsonSubtypes.KnownSubType(typeof(Mortgage), "mortgage")]
    [JsonSubtypes.KnownSubType(typeof(Option), "option")]
    [JsonSubtypes.KnownSubType(typeof(OtherFinancialInstrument), "other")]
    [JsonSubtypes.KnownSubType(typeof(TotalReturnSwap), "totalReturnSwap")]
    public partial class FinancialInstrument : IEquatable<FinancialInstrument>
    {
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public FinancialInstrumentType Type { get; set; }

        /// <summary>
        /// Name of the financial instrument in free format text.
        /// </summary>
        /// <value>Name of the financial instrument in free format text.</value>
        /// <example>Novartis AG</example>
        [Required]
        [MaxLength(170)]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// List of identification objects.
        /// </summary>
        /// <value>List of identification objects.</value>
        [DataMember(Name="identificationList", EmitDefaultValue=false)]
        public List<FinancialInstrumentIdentification> IdentificationList { get; set; }

        /// <summary>
        /// Indicates the type of the financial instrument. Must follow the ISO 10962, which is also known as CFI (classification of financial instruments). At least indicate the CFI Category (1st character) and the CFI Group (2nd character). The CFI attributes 1-4 (3rd to 6th character in the string) are optional. 
        /// </summary>
        /// <value>Indicates the type of the financial instrument. Must follow the ISO 10962, which is also known as CFI (classification of financial instruments). At least indicate the CFI Category (1st character) and the CFI Group (2nd character). The CFI attributes 1-4 (3rd to 6th character in the string) are optional. </value>
        /// <example>ESVUFR</example>
        [RegularExpression("^[A-Z]{2,6}$")]
        [StringLength(6, MinimumLength=2)]
        [DataMember(Name="cfiCode", EmitDefaultValue=false)]
        public string? CfiCode { get; set; }

        /// <summary>
        /// ISO 4217 code.
        /// </summary>
        /// <value>ISO 4217 code.</value>
        /// <example>CHF</example>
        [RegularExpression("^[A-Z]{3}$")]
        [DataMember(Name="currencyOfDenomination", EmitDefaultValue=false)]
        public string? CurrencyOfDenomination { get; set; }

        /// <summary>
        /// Indicates if there is a factor present for this financial instrument. If this indicator is set to TRUE, but the factor attribute is not present, might indicate, that the factor cannot be delivered or is currently not available. 
        /// </summary>
        /// <value>Indicates if there is a factor present for this financial instrument. If this indicator is set to TRUE, but the factor attribute is not present, might indicate, that the factor cannot be delivered or is currently not available. </value>
        /// <example>true</example>
        [DataMember(Name="hasFactor", EmitDefaultValue=true)]
        public bool? HasFactor { get; set; }

        /// <summary>
        /// Information regarding the factor.
        /// </summary>
        /// <value>Information regarding the factor.</value>
        /// <example>0.85</example>
        [DataMember(Name="factor", EmitDefaultValue=true)]
        public decimal? Factor { get; set; }

        /// <summary>
        /// Provides additional information about the financial instrument in narrative form.
        /// </summary>
        /// <value>Provides additional information about the financial instrument in narrative form.</value>
        /// <example>Group contract number 129959961</example>
        [MaxLength(70)]
        [DataMember(Name="additionalDetails", EmitDefaultValue=false)]
        public string? AdditionalDetails { get; set; }

        /// <summary>
        /// Gets or Sets InterestRate
        /// </summary>
        [DataMember(Name="interestRate", EmitDefaultValue=false)]
        public InterestRate? InterestRate { get; set; }

        /// <summary>
        /// Date according to ISO 8601.
        /// </summary>
        /// <value>Date according to ISO 8601.</value>
        /// <example>Fri Apr 13 02:00:00 CEST 2018</example>
        [Required]
        [DataMember(Name="maturityDate", EmitDefaultValue=true)]
        public DateOnly MaturityDate { get; set; }

        /// <summary>
        /// Date according to ISO 8601.
        /// </summary>
        /// <value>Date according to ISO 8601.</value>
        /// <example>Fri Apr 13 02:00:00 CEST 2018</example>
        [DataMember(Name="issueDate", EmitDefaultValue=true)]
        public DateOnly? IssueDate { get; set; }

        /// <summary>
        /// Gets or Sets ConversionPrice
        /// </summary>
        [DataMember(Name="conversionPrice", EmitDefaultValue=false)]
        public Price? ConversionPrice { get; set; }

        /// <summary>
        /// Indicates the minimum denomination of a security.
        /// </summary>
        /// <value>Indicates the minimum denomination of a security.</value>
        /// <example>10000</example>
        [DataMember(Name="minimumDenomination", EmitDefaultValue=true)]
        public decimal? MinimumDenomination { get; set; }

        /// <summary>
        /// Indicates the minimum tradable increments of a security.
        /// </summary>
        /// <value>Indicates the minimum tradable increments of a security.</value>
        /// <example>1000</example>
        [DataMember(Name="minimumIncrement", EmitDefaultValue=true)]
        public decimal? MinimumIncrement { get; set; }

        /// <summary>
        /// Gets or Sets UnderlyingFinancialInstrument
        /// </summary>
        [Required]
        [DataMember(Name="underlyingFinancialInstrument", EmitDefaultValue=false)]
        public FinancialInstrument UnderlyingFinancialInstrument { get; set; }

        /// <summary>
        /// Date according to ISO 8601.
        /// </summary>
        /// <value>Date according to ISO 8601.</value>
        /// <example>Fri Apr 13 02:00:00 CEST 2018</example>
        [DataMember(Name="expiryDate", EmitDefaultValue=true)]
        public DateOnly? ExpiryDate { get; set; }

        /// <summary>
        /// Gets or Sets ExercisePrice
        /// </summary>
        [DataMember(Name="exercisePrice", EmitDefaultValue=false)]
        public Price? ExercisePrice { get; set; }

        /// <summary>
        /// Contract size of the instrument.
        /// </summary>
        /// <value>Contract size of the instrument.</value>
        /// <example>100</example>
        [DataMember(Name="contractSize", EmitDefaultValue=true)]
        public decimal? ContractSize { get; set; } = 1M;

        /// <summary>
        /// Gets or Sets OptionType
        /// </summary>
        [DataMember(Name="optionType", EmitDefaultValue=true)]
        public OptionType OptionType { get; set; }

        /// <summary>
        /// Gets or Sets OptionStyle
        /// </summary>
        [DataMember(Name="optionStyle", EmitDefaultValue=true)]
        public OptionStyle OptionStyle { get; set; }

        /// <summary>
        /// Gets or Sets AmountPaid
        /// </summary>
        [Required]
        [DataMember(Name="amountPaid", EmitDefaultValue=false)]
        public CurrencyAmount AmountPaid { get; set; }

        /// <summary>
        /// Gets or Sets AmountReceived
        /// </summary>
        [Required]
        [DataMember(Name="amountReceived", EmitDefaultValue=false)]
        public CurrencyAmount AmountReceived { get; set; }

        /// <summary>
        /// Gets or Sets NearAmountPaid
        /// </summary>
        [Required]
        [DataMember(Name="nearAmountPaid", EmitDefaultValue=false)]
        public CurrencyAmount NearAmountPaid { get; set; }

        /// <summary>
        /// Gets or Sets NearAmountReceived
        /// </summary>
        [Required]
        [DataMember(Name="nearAmountReceived", EmitDefaultValue=false)]
        public CurrencyAmount NearAmountReceived { get; set; }

        /// <summary>
        /// Gets or Sets FarAmountPaid
        /// </summary>
        [Required]
        [DataMember(Name="farAmountPaid", EmitDefaultValue=false)]
        public CurrencyAmount FarAmountPaid { get; set; }

        /// <summary>
        /// Gets or Sets FarAmountReceived
        /// </summary>
        [Required]
        [DataMember(Name="farAmountReceived", EmitDefaultValue=false)]
        public CurrencyAmount FarAmountReceived { get; set; }

        /// <summary>
        /// Date according to ISO 8601.
        /// </summary>
        /// <value>Date according to ISO 8601.</value>
        /// <example>Fri Apr 13 02:00:00 CEST 2018</example>
        [Required]
        [DataMember(Name="nearMaturityDate", EmitDefaultValue=true)]
        public DateOnly NearMaturityDate { get; set; }

        /// <summary>
        /// DateTime according to ISO 8601.
        /// </summary>
        /// <value>DateTime according to ISO 8601.</value>
        /// <example>2018-04-13T16:00+01:00</example>
        [Required]
        [DataMember(Name="expiryDateTime", EmitDefaultValue=true)]
        public DateTime ExpiryDateTime { get; set; }

        /// <summary>
        /// Gets or Sets UnderlyingAmount
        /// </summary>
        [Required]
        [DataMember(Name="underlyingAmount", EmitDefaultValue=false)]
        public CurrencyAmount UnderlyingAmount { get; set; }

        /// <summary>
        /// Gets or Sets CounterAmount
        /// </summary>
        [Required]
        [DataMember(Name="counterAmount", EmitDefaultValue=false)]
        public CurrencyAmount CounterAmount { get; set; }

        /// <summary>
        /// Gets or Sets Premium
        /// </summary>
        [DataMember(Name="premium", EmitDefaultValue=false)]
        public CurrencyAmount? Premium { get; set; }

        /// <summary>
        /// Gets or Sets PrincipalAmount
        /// </summary>
        [Required]
        [DataMember(Name="principalAmount", EmitDefaultValue=false)]
        public CurrencyAmount PrincipalAmount { get; set; }

        /// <summary>
        /// Maximum principal amount allowed by the credit contract.
        /// </summary>
        /// <value>Maximum principal amount allowed by the credit contract.</value>
        /// <example>100000</example>
        [DataMember(Name="limit", EmitDefaultValue=true)]
        public decimal? Limit { get; set; }

        /// <summary>
        /// Gets or Sets NotionalAmount
        /// </summary>
        [Required]
        [DataMember(Name="notionalAmount", EmitDefaultValue=false)]
        public CurrencyAmount NotionalAmount { get; set; }

        /// <summary>
        /// Gets or Sets InterestRatePaid
        /// </summary>
        [Required]
        [DataMember(Name="interestRatePaid", EmitDefaultValue=false)]
        public InterestRate InterestRatePaid { get; set; }

        /// <summary>
        /// Gets or Sets InterestRateReceived
        /// </summary>
        [Required]
        [DataMember(Name="interestRateReceived", EmitDefaultValue=false)]
        public InterestRate InterestRateReceived { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FinancialInstrument {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IdentificationList: ").Append(IdentificationList).Append("\n");
            sb.Append("  CfiCode: ").Append(CfiCode).Append("\n");
            sb.Append("  CurrencyOfDenomination: ").Append(CurrencyOfDenomination).Append("\n");
            sb.Append("  HasFactor: ").Append(HasFactor).Append("\n");
            sb.Append("  Factor: ").Append(Factor).Append("\n");
            sb.Append("  AdditionalDetails: ").Append(AdditionalDetails).Append("\n");
            sb.Append("  InterestRate: ").Append(InterestRate).Append("\n");
            sb.Append("  MaturityDate: ").Append(MaturityDate).Append("\n");
            sb.Append("  IssueDate: ").Append(IssueDate).Append("\n");
            sb.Append("  ConversionPrice: ").Append(ConversionPrice).Append("\n");
            sb.Append("  MinimumDenomination: ").Append(MinimumDenomination).Append("\n");
            sb.Append("  MinimumIncrement: ").Append(MinimumIncrement).Append("\n");
            sb.Append("  UnderlyingFinancialInstrument: ").Append(UnderlyingFinancialInstrument).Append("\n");
            sb.Append("  ExpiryDate: ").Append(ExpiryDate).Append("\n");
            sb.Append("  ExercisePrice: ").Append(ExercisePrice).Append("\n");
            sb.Append("  ContractSize: ").Append(ContractSize).Append("\n");
            sb.Append("  OptionType: ").Append(OptionType).Append("\n");
            sb.Append("  OptionStyle: ").Append(OptionStyle).Append("\n");
            sb.Append("  AmountPaid: ").Append(AmountPaid).Append("\n");
            sb.Append("  AmountReceived: ").Append(AmountReceived).Append("\n");
            sb.Append("  NearAmountPaid: ").Append(NearAmountPaid).Append("\n");
            sb.Append("  NearAmountReceived: ").Append(NearAmountReceived).Append("\n");
            sb.Append("  FarAmountPaid: ").Append(FarAmountPaid).Append("\n");
            sb.Append("  FarAmountReceived: ").Append(FarAmountReceived).Append("\n");
            sb.Append("  NearMaturityDate: ").Append(NearMaturityDate).Append("\n");
            sb.Append("  ExpiryDateTime: ").Append(ExpiryDateTime).Append("\n");
            sb.Append("  UnderlyingAmount: ").Append(UnderlyingAmount).Append("\n");
            sb.Append("  CounterAmount: ").Append(CounterAmount).Append("\n");
            sb.Append("  Premium: ").Append(Premium).Append("\n");
            sb.Append("  PrincipalAmount: ").Append(PrincipalAmount).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  NotionalAmount: ").Append(NotionalAmount).Append("\n");
            sb.Append("  InterestRatePaid: ").Append(InterestRatePaid).Append("\n");
            sb.Append("  InterestRateReceived: ").Append(InterestRateReceived).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FinancialInstrument)obj);
        }

        /// <summary>
        /// Returns true if FinancialInstrument instances are equal
        /// </summary>
        /// <param name="other">Instance of FinancialInstrument to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FinancialInstrument other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Type == other.Type ||
                    
                    Type.Equals(other.Type)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    IdentificationList == other.IdentificationList ||
                    IdentificationList != null &&
                    other.IdentificationList != null &&
                    IdentificationList.SequenceEqual(other.IdentificationList)
                ) && 
                (
                    CfiCode == other.CfiCode ||
                    CfiCode != null &&
                    CfiCode.Equals(other.CfiCode)
                ) && 
                (
                    CurrencyOfDenomination == other.CurrencyOfDenomination ||
                    CurrencyOfDenomination != null &&
                    CurrencyOfDenomination.Equals(other.CurrencyOfDenomination)
                ) && 
                (
                    HasFactor == other.HasFactor ||
                    
                    HasFactor.Equals(other.HasFactor)
                ) && 
                (
                    Factor == other.Factor ||
                    
                    Factor.Equals(other.Factor)
                ) && 
                (
                    AdditionalDetails == other.AdditionalDetails ||
                    AdditionalDetails != null &&
                    AdditionalDetails.Equals(other.AdditionalDetails)
                ) && 
                (
                    InterestRate == other.InterestRate ||
                    InterestRate != null &&
                    InterestRate.Equals(other.InterestRate)
                ) && 
                (
                    MaturityDate == other.MaturityDate ||
                    
                    MaturityDate.Equals(other.MaturityDate)
                ) && 
                (
                    IssueDate == other.IssueDate ||
                    
                    IssueDate.Equals(other.IssueDate)
                ) && 
                (
                    ConversionPrice == other.ConversionPrice ||
                    ConversionPrice != null &&
                    ConversionPrice.Equals(other.ConversionPrice)
                ) && 
                (
                    MinimumDenomination == other.MinimumDenomination ||
                    
                    MinimumDenomination.Equals(other.MinimumDenomination)
                ) && 
                (
                    MinimumIncrement == other.MinimumIncrement ||
                    
                    MinimumIncrement.Equals(other.MinimumIncrement)
                ) && 
                (
                    UnderlyingFinancialInstrument == other.UnderlyingFinancialInstrument ||
                    UnderlyingFinancialInstrument != null &&
                    UnderlyingFinancialInstrument.Equals(other.UnderlyingFinancialInstrument)
                ) && 
                (
                    ExpiryDate == other.ExpiryDate ||
                    
                    ExpiryDate.Equals(other.ExpiryDate)
                ) && 
                (
                    ExercisePrice == other.ExercisePrice ||
                    ExercisePrice != null &&
                    ExercisePrice.Equals(other.ExercisePrice)
                ) && 
                (
                    ContractSize == other.ContractSize ||
                    
                    ContractSize.Equals(other.ContractSize)
                ) && 
                (
                    OptionType == other.OptionType ||
                    
                    OptionType.Equals(other.OptionType)
                ) && 
                (
                    OptionStyle == other.OptionStyle ||
                    
                    OptionStyle.Equals(other.OptionStyle)
                ) && 
                (
                    AmountPaid == other.AmountPaid ||
                    AmountPaid != null &&
                    AmountPaid.Equals(other.AmountPaid)
                ) && 
                (
                    AmountReceived == other.AmountReceived ||
                    AmountReceived != null &&
                    AmountReceived.Equals(other.AmountReceived)
                ) && 
                (
                    NearAmountPaid == other.NearAmountPaid ||
                    NearAmountPaid != null &&
                    NearAmountPaid.Equals(other.NearAmountPaid)
                ) && 
                (
                    NearAmountReceived == other.NearAmountReceived ||
                    NearAmountReceived != null &&
                    NearAmountReceived.Equals(other.NearAmountReceived)
                ) && 
                (
                    FarAmountPaid == other.FarAmountPaid ||
                    FarAmountPaid != null &&
                    FarAmountPaid.Equals(other.FarAmountPaid)
                ) && 
                (
                    FarAmountReceived == other.FarAmountReceived ||
                    FarAmountReceived != null &&
                    FarAmountReceived.Equals(other.FarAmountReceived)
                ) && 
                (
                    NearMaturityDate == other.NearMaturityDate ||
                    
                    NearMaturityDate.Equals(other.NearMaturityDate)
                ) && 
                (
                    ExpiryDateTime == other.ExpiryDateTime ||
                    
                    ExpiryDateTime.Equals(other.ExpiryDateTime)
                ) && 
                (
                    UnderlyingAmount == other.UnderlyingAmount ||
                    UnderlyingAmount != null &&
                    UnderlyingAmount.Equals(other.UnderlyingAmount)
                ) && 
                (
                    CounterAmount == other.CounterAmount ||
                    CounterAmount != null &&
                    CounterAmount.Equals(other.CounterAmount)
                ) && 
                (
                    Premium == other.Premium ||
                    Premium != null &&
                    Premium.Equals(other.Premium)
                ) && 
                (
                    PrincipalAmount == other.PrincipalAmount ||
                    PrincipalAmount != null &&
                    PrincipalAmount.Equals(other.PrincipalAmount)
                ) && 
                (
                    Limit == other.Limit ||
                    
                    Limit.Equals(other.Limit)
                ) && 
                (
                    NotionalAmount == other.NotionalAmount ||
                    NotionalAmount != null &&
                    NotionalAmount.Equals(other.NotionalAmount)
                ) && 
                (
                    InterestRatePaid == other.InterestRatePaid ||
                    InterestRatePaid != null &&
                    InterestRatePaid.Equals(other.InterestRatePaid)
                ) && 
                (
                    InterestRateReceived == other.InterestRateReceived ||
                    InterestRateReceived != null &&
                    InterestRateReceived.Equals(other.InterestRateReceived)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Type.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (IdentificationList != null)
                    hashCode = hashCode * 59 + IdentificationList.GetHashCode();
                    if (CfiCode != null)
                    hashCode = hashCode * 59 + CfiCode.GetHashCode();
                    if (CurrencyOfDenomination != null)
                    hashCode = hashCode * 59 + CurrencyOfDenomination.GetHashCode();
                    
                    hashCode = hashCode * 59 + HasFactor.GetHashCode();
                    
                    hashCode = hashCode * 59 + Factor.GetHashCode();
                    if (AdditionalDetails != null)
                    hashCode = hashCode * 59 + AdditionalDetails.GetHashCode();
                    if (InterestRate != null)
                    hashCode = hashCode * 59 + InterestRate.GetHashCode();
                    
                    hashCode = hashCode * 59 + MaturityDate.GetHashCode();
                    
                    hashCode = hashCode * 59 + IssueDate.GetHashCode();
                    if (ConversionPrice != null)
                    hashCode = hashCode * 59 + ConversionPrice.GetHashCode();
                    
                    hashCode = hashCode * 59 + MinimumDenomination.GetHashCode();
                    
                    hashCode = hashCode * 59 + MinimumIncrement.GetHashCode();
                    if (UnderlyingFinancialInstrument != null)
                    hashCode = hashCode * 59 + UnderlyingFinancialInstrument.GetHashCode();
                    
                    hashCode = hashCode * 59 + ExpiryDate.GetHashCode();
                    if (ExercisePrice != null)
                    hashCode = hashCode * 59 + ExercisePrice.GetHashCode();
                    
                    hashCode = hashCode * 59 + ContractSize.GetHashCode();
                    
                    hashCode = hashCode * 59 + OptionType.GetHashCode();
                    
                    hashCode = hashCode * 59 + OptionStyle.GetHashCode();
                    if (AmountPaid != null)
                    hashCode = hashCode * 59 + AmountPaid.GetHashCode();
                    if (AmountReceived != null)
                    hashCode = hashCode * 59 + AmountReceived.GetHashCode();
                    if (NearAmountPaid != null)
                    hashCode = hashCode * 59 + NearAmountPaid.GetHashCode();
                    if (NearAmountReceived != null)
                    hashCode = hashCode * 59 + NearAmountReceived.GetHashCode();
                    if (FarAmountPaid != null)
                    hashCode = hashCode * 59 + FarAmountPaid.GetHashCode();
                    if (FarAmountReceived != null)
                    hashCode = hashCode * 59 + FarAmountReceived.GetHashCode();
                    
                    hashCode = hashCode * 59 + NearMaturityDate.GetHashCode();
                    
                    hashCode = hashCode * 59 + ExpiryDateTime.GetHashCode();
                    if (UnderlyingAmount != null)
                    hashCode = hashCode * 59 + UnderlyingAmount.GetHashCode();
                    if (CounterAmount != null)
                    hashCode = hashCode * 59 + CounterAmount.GetHashCode();
                    if (Premium != null)
                    hashCode = hashCode * 59 + Premium.GetHashCode();
                    if (PrincipalAmount != null)
                    hashCode = hashCode * 59 + PrincipalAmount.GetHashCode();
                    
                    hashCode = hashCode * 59 + Limit.GetHashCode();
                    if (NotionalAmount != null)
                    hashCode = hashCode * 59 + NotionalAmount.GetHashCode();
                    if (InterestRatePaid != null)
                    hashCode = hashCode * 59 + InterestRatePaid.GetHashCode();
                    if (InterestRateReceived != null)
                    hashCode = hashCode * 59 + InterestRateReceived.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(FinancialInstrument left, FinancialInstrument right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FinancialInstrument left, FinancialInstrument right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
