/*
 * Custody Services
 *
 * This API is part of the OpenWealth APIs for the connectivity between custody banks and WealthTechs (e.g. Portfolio Management Systems). This API allows the user to receive data from custody banks regarding accounts and positions. The API is designed to be used for either update end of day data batches or single near-realtime account/position information. Furthermore, this API allows the user to receive data from custody banks regarding transactions. In this version (2.0) only transactions which include effective cash or securities movements are in scope and corporate actions without any cash impact are delivered only on a informative basis. 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: openwealth@synpulse.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using OpenWealth.Converters;

namespace OpenWealth.Models
{ 
    /// <summary>
    /// An exchange rate is a rate at which one currency will be exchanged for another currency.
    /// </summary>
    [DataContract]
    public partial class ForeignExchangeRate : IEquatable<ForeignExchangeRate>
    {
        /// <summary>
        /// Current rate as decimal.
        /// </summary>
        /// <value>Current rate as decimal.</value>
        /// <example>0.98</example>
        [Required]
        [DataMember(Name="value", EmitDefaultValue=true)]
        public decimal Value { get; set; }

        /// <summary>
        /// ISO 4217 code.
        /// </summary>
        /// <value>ISO 4217 code.</value>
        /// <example>CHF</example>
        [Required]
        [RegularExpression("^[A-Z]{3}$")]
        [DataMember(Name="sourceCurrency", EmitDefaultValue=false)]
        public string SourceCurrency { get; set; }

        /// <summary>
        /// ISO 4217 code.
        /// </summary>
        /// <value>ISO 4217 code.</value>
        /// <example>CHF</example>
        [Required]
        [RegularExpression("^[A-Z]{3}$")]
        [DataMember(Name="targetCurrency", EmitDefaultValue=false)]
        public string TargetCurrency { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ForeignExchangeRate {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  SourceCurrency: ").Append(SourceCurrency).Append("\n");
            sb.Append("  TargetCurrency: ").Append(TargetCurrency).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ForeignExchangeRate)obj);
        }

        /// <summary>
        /// Returns true if ForeignExchangeRate instances are equal
        /// </summary>
        /// <param name="other">Instance of ForeignExchangeRate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ForeignExchangeRate other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Value == other.Value ||
                    
                    Value.Equals(other.Value)
                ) && 
                (
                    SourceCurrency == other.SourceCurrency ||
                    SourceCurrency != null &&
                    SourceCurrency.Equals(other.SourceCurrency)
                ) && 
                (
                    TargetCurrency == other.TargetCurrency ||
                    TargetCurrency != null &&
                    TargetCurrency.Equals(other.TargetCurrency)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Value.GetHashCode();
                    if (SourceCurrency != null)
                    hashCode = hashCode * 59 + SourceCurrency.GetHashCode();
                    if (TargetCurrency != null)
                    hashCode = hashCode * 59 + TargetCurrency.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ForeignExchangeRate left, ForeignExchangeRate right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ForeignExchangeRate left, ForeignExchangeRate right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
