/*
 * Custody Services
 *
 * This API is part of the OpenWealth APIs for the connectivity between custody banks and WealthTechs (e.g. Portfolio Management Systems). This API allows the user to receive data from custody banks regarding accounts and positions. The API is designed to be used for either update end of day data batches or single near-realtime account/position information. Furthermore, this API allows the user to receive data from custody banks regarding transactions. In this version (2.0) only transactions which include effective cash or securities movements are in scope and corporate actions without any cash impact are delivered only on a informative basis. 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: openwealth@synpulse.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using OpenWealth.Converters;

namespace OpenWealth.Models
{ 
    /// <summary>
    /// An FX option is a contract that gives the buyer the right, but not the obligation, to buy or sell a certain currency at a specified exchange rate on or before a specified date. For this right, a premium is paid to the seller. 
    /// </summary>
    [DataContract]
    public partial class FxOption : IEquatable<FxOption>
    {
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public FinancialInstrumentType Type { get; set; }

        /// <summary>
        /// Name of the financial instrument in free format text.
        /// </summary>
        /// <value>Name of the financial instrument in free format text.</value>
        /// <example>Novartis AG</example>
        [Required]
        [MaxLength(170)]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// List of identification objects.
        /// </summary>
        /// <value>List of identification objects.</value>
        [DataMember(Name="identificationList", EmitDefaultValue=false)]
        public List<FinancialInstrumentIdentification> IdentificationList { get; set; }

        /// <summary>
        /// Indicates the type of the financial instrument. Must follow the ISO 10962, which is also known as CFI (classification of financial instruments). At least indicate the CFI Category (1st character) and the CFI Group (2nd character). The CFI attributes 1-4 (3rd to 6th character in the string) are optional. 
        /// </summary>
        /// <value>Indicates the type of the financial instrument. Must follow the ISO 10962, which is also known as CFI (classification of financial instruments). At least indicate the CFI Category (1st character) and the CFI Group (2nd character). The CFI attributes 1-4 (3rd to 6th character in the string) are optional. </value>
        /// <example>ESVUFR</example>
        [RegularExpression("^[A-Z]{2,6}$")]
        [StringLength(6, MinimumLength=2)]
        [DataMember(Name="cfiCode", EmitDefaultValue=false)]
        public string? CfiCode { get; set; }

        /// <summary>
        /// ISO 4217 code.
        /// </summary>
        /// <value>ISO 4217 code.</value>
        /// <example>CHF</example>
        [RegularExpression("^[A-Z]{3}$")]
        [DataMember(Name="currencyOfDenomination", EmitDefaultValue=false)]
        public string? CurrencyOfDenomination { get; set; }

        /// <summary>
        /// Indicates if there is a factor present for this financial instrument. If this indicator is set to TRUE, but the factor attribute is not present, might indicate, that the factor cannot be delivered or is currently not available. 
        /// </summary>
        /// <value>Indicates if there is a factor present for this financial instrument. If this indicator is set to TRUE, but the factor attribute is not present, might indicate, that the factor cannot be delivered or is currently not available. </value>
        /// <example>true</example>
        [DataMember(Name="hasFactor", EmitDefaultValue=true)]
        public bool? HasFactor { get; set; }

        /// <summary>
        /// Information regarding the factor.
        /// </summary>
        /// <value>Information regarding the factor.</value>
        /// <example>0.85</example>
        [DataMember(Name="factor", EmitDefaultValue=true)]
        public decimal? Factor { get; set; }

        /// <summary>
        /// Provides additional information about the financial instrument in narrative form.
        /// </summary>
        /// <value>Provides additional information about the financial instrument in narrative form.</value>
        /// <example>Group contract number 129959961</example>
        [MaxLength(70)]
        [DataMember(Name="additionalDetails", EmitDefaultValue=false)]
        public string? AdditionalDetails { get; set; }

        /// <summary>
        /// DateTime according to ISO 8601.
        /// </summary>
        /// <value>DateTime according to ISO 8601.</value>
        /// <example>2018-04-13T16:00+01:00</example>
        [Required]
        [DataMember(Name="expiryDateTime", EmitDefaultValue=true)]
        public DateTime ExpiryDateTime { get; set; }

        /// <summary>
        /// Gets or Sets UnderlyingAmount
        /// </summary>
        [Required]
        [DataMember(Name="underlyingAmount", EmitDefaultValue=false)]
        public CurrencyAmount UnderlyingAmount { get; set; }

        /// <summary>
        /// Gets or Sets CounterAmount
        /// </summary>
        [Required]
        [DataMember(Name="counterAmount", EmitDefaultValue=false)]
        public CurrencyAmount CounterAmount { get; set; }

        /// <summary>
        /// Gets or Sets Premium
        /// </summary>
        [DataMember(Name="premium", EmitDefaultValue=false)]
        public CurrencyAmount? Premium { get; set; }

        /// <summary>
        /// Gets or Sets OptionType
        /// </summary>
        [DataMember(Name="optionType", EmitDefaultValue=true)]
        public OptionType OptionType { get; set; }

        /// <summary>
        /// Gets or Sets OptionStyle
        /// </summary>
        [DataMember(Name="optionStyle", EmitDefaultValue=true)]
        public OptionStyle OptionStyle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FxOption {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IdentificationList: ").Append(IdentificationList).Append("\n");
            sb.Append("  CfiCode: ").Append(CfiCode).Append("\n");
            sb.Append("  CurrencyOfDenomination: ").Append(CurrencyOfDenomination).Append("\n");
            sb.Append("  HasFactor: ").Append(HasFactor).Append("\n");
            sb.Append("  Factor: ").Append(Factor).Append("\n");
            sb.Append("  AdditionalDetails: ").Append(AdditionalDetails).Append("\n");
            sb.Append("  ExpiryDateTime: ").Append(ExpiryDateTime).Append("\n");
            sb.Append("  UnderlyingAmount: ").Append(UnderlyingAmount).Append("\n");
            sb.Append("  CounterAmount: ").Append(CounterAmount).Append("\n");
            sb.Append("  Premium: ").Append(Premium).Append("\n");
            sb.Append("  OptionType: ").Append(OptionType).Append("\n");
            sb.Append("  OptionStyle: ").Append(OptionStyle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FxOption)obj);
        }

        /// <summary>
        /// Returns true if FxOption instances are equal
        /// </summary>
        /// <param name="other">Instance of FxOption to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FxOption other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Type == other.Type ||
                    
                    Type.Equals(other.Type)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    IdentificationList == other.IdentificationList ||
                    IdentificationList != null &&
                    other.IdentificationList != null &&
                    IdentificationList.SequenceEqual(other.IdentificationList)
                ) && 
                (
                    CfiCode == other.CfiCode ||
                    CfiCode != null &&
                    CfiCode.Equals(other.CfiCode)
                ) && 
                (
                    CurrencyOfDenomination == other.CurrencyOfDenomination ||
                    CurrencyOfDenomination != null &&
                    CurrencyOfDenomination.Equals(other.CurrencyOfDenomination)
                ) && 
                (
                    HasFactor == other.HasFactor ||
                    
                    HasFactor.Equals(other.HasFactor)
                ) && 
                (
                    Factor == other.Factor ||
                    
                    Factor.Equals(other.Factor)
                ) && 
                (
                    AdditionalDetails == other.AdditionalDetails ||
                    AdditionalDetails != null &&
                    AdditionalDetails.Equals(other.AdditionalDetails)
                ) && 
                (
                    ExpiryDateTime == other.ExpiryDateTime ||
                    
                    ExpiryDateTime.Equals(other.ExpiryDateTime)
                ) && 
                (
                    UnderlyingAmount == other.UnderlyingAmount ||
                    UnderlyingAmount != null &&
                    UnderlyingAmount.Equals(other.UnderlyingAmount)
                ) && 
                (
                    CounterAmount == other.CounterAmount ||
                    CounterAmount != null &&
                    CounterAmount.Equals(other.CounterAmount)
                ) && 
                (
                    Premium == other.Premium ||
                    Premium != null &&
                    Premium.Equals(other.Premium)
                ) && 
                (
                    OptionType == other.OptionType ||
                    
                    OptionType.Equals(other.OptionType)
                ) && 
                (
                    OptionStyle == other.OptionStyle ||
                    
                    OptionStyle.Equals(other.OptionStyle)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Type.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (IdentificationList != null)
                    hashCode = hashCode * 59 + IdentificationList.GetHashCode();
                    if (CfiCode != null)
                    hashCode = hashCode * 59 + CfiCode.GetHashCode();
                    if (CurrencyOfDenomination != null)
                    hashCode = hashCode * 59 + CurrencyOfDenomination.GetHashCode();
                    
                    hashCode = hashCode * 59 + HasFactor.GetHashCode();
                    
                    hashCode = hashCode * 59 + Factor.GetHashCode();
                    if (AdditionalDetails != null)
                    hashCode = hashCode * 59 + AdditionalDetails.GetHashCode();
                    
                    hashCode = hashCode * 59 + ExpiryDateTime.GetHashCode();
                    if (UnderlyingAmount != null)
                    hashCode = hashCode * 59 + UnderlyingAmount.GetHashCode();
                    if (CounterAmount != null)
                    hashCode = hashCode * 59 + CounterAmount.GetHashCode();
                    if (Premium != null)
                    hashCode = hashCode * 59 + Premium.GetHashCode();
                    
                    hashCode = hashCode * 59 + OptionType.GetHashCode();
                    
                    hashCode = hashCode * 59 + OptionStyle.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(FxOption left, FxOption right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FxOption left, FxOption right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
