/*
 * Custody Services
 *
 * This API is part of the OpenWealth APIs for the connectivity between custody banks and WealthTechs (e.g. Portfolio Management Systems). This API allows the user to receive data from custody banks regarding accounts and positions. The API is designed to be used for either update end of day data batches or single near-realtime account/position information. Furthermore, this API allows the user to receive data from custody banks regarding transactions. In this version (2.0) only transactions which include effective cash or securities movements are in scope and corporate actions without any cash impact are delivered only on a informative basis. 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: openwealth@synpulse.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using OpenWealth.Converters;

namespace OpenWealth.Models
{
    /// <summary>
    /// Specifies how an option can be exercised.
    /// </summary>
    /// <value>Specifies how an option can be exercised.</value>

    public enum OptionStyle
    {

        /// <summary>
        /// Enum American for american
        /// </summary>
        [EnumMember(Value = "american")]
        American = 1,

        /// <summary>
        /// Enum European for european
        /// </summary>
        [EnumMember(Value = "european")]
        European = 2,

        /// <summary>
        /// Enum Bermudan for bermudan
        /// </summary>
        [EnumMember(Value = "bermudan")]
        Bermudan = 3,

        /// <summary>
        /// Enum Asian for asian
        /// </summary>
        [EnumMember(Value = "asian")]
        Asian = 4
    }
}
