/*
 * Custody Services
 *
 * This API is part of the OpenWealth APIs for the connectivity between custody banks and WealthTechs (e.g. Portfolio Management Systems). This API allows the user to receive data from custody banks regarding accounts and positions. The API is designed to be used for either update end of day data batches or single near-realtime account/position information. Furthermore, this API allows the user to receive data from custody banks regarding transactions. In this version (2.0) only transactions which include effective cash or securities movements are in scope and corporate actions without any cash impact are delivered only on a informative basis. 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: openwealth@synpulse.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using OpenWealth.Converters;

namespace OpenWealth.Models
{ 
    /// <summary>
    /// Information about the portfolio.
    /// </summary>
    [DataContract]
    public partial class PortfolioInformation : IEquatable<PortfolioInformation>
    {
        /// <summary>
        /// Unique and unambiguous identification for the portfolio between the portfolio owner and the portfolio servicer.
        /// </summary>
        /// <value>Unique and unambiguous identification for the portfolio between the portfolio owner and the portfolio servicer.</value>
        /// <example>87654-3219</example>
        [StringLength(128, MinimumLength=1)]
        [DataMember(Name="identification", EmitDefaultValue=false)]
        public string? Identification { get; set; }

        /// <summary>
        /// ISO 4217 code.
        /// </summary>
        /// <value>ISO 4217 code.</value>
        /// <example>CHF</example>
        [RegularExpression("^[A-Z]{3}$")]
        [DataMember(Name="referenceCurrency", EmitDefaultValue=false)]
        public string? ReferenceCurrency { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PortfolioInformation {\n");
            sb.Append("  Identification: ").Append(Identification).Append("\n");
            sb.Append("  ReferenceCurrency: ").Append(ReferenceCurrency).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PortfolioInformation)obj);
        }

        /// <summary>
        /// Returns true if PortfolioInformation instances are equal
        /// </summary>
        /// <param name="other">Instance of PortfolioInformation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PortfolioInformation other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Identification == other.Identification ||
                    Identification != null &&
                    Identification.Equals(other.Identification)
                ) && 
                (
                    ReferenceCurrency == other.ReferenceCurrency ||
                    ReferenceCurrency != null &&
                    ReferenceCurrency.Equals(other.ReferenceCurrency)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Identification != null)
                    hashCode = hashCode * 59 + Identification.GetHashCode();
                    if (ReferenceCurrency != null)
                    hashCode = hashCode * 59 + ReferenceCurrency.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PortfolioInformation left, PortfolioInformation right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PortfolioInformation left, PortfolioInformation right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
