/*
 * Custody Services
 *
 * This API is part of the OpenWealth APIs for the connectivity between custody banks and WealthTechs (e.g. Portfolio Management Systems). This API allows the user to receive data from custody banks regarding accounts and positions. The API is designed to be used for either update end of day data batches or single near-realtime account/position information. Furthermore, this API allows the user to receive data from custody banks regarding transactions. In this version (2.0) only transactions which include effective cash or securities movements are in scope and corporate actions without any cash impact are delivered only on a informative basis. 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: openwealth@synpulse.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using OpenWealth.Converters;

namespace OpenWealth.Models
{
    /// <summary>
    /// Quantity entity.
    /// </summary>
    [DataContract]
    public partial class Quantity : IEquatable<Quantity>
    {

        /// <summary>
        /// Specifies the type of the amount.
        /// </summary>
        /// <value>Specifies the type of the amount.</value>

        public enum TypeEnum
        {

            /// <summary>
            /// Enum Unit for unit
            /// </summary>
            [EnumMember(Value = "unit")]
            Unit = 1,

            /// <summary>
            /// Enum FaceAmount for faceAmount
            /// </summary>
            [EnumMember(Value = "faceAmount")]
            FaceAmount = 2,

            /// <summary>
            /// Enum AmortisedValue for amortisedValue
            /// </summary>
            [EnumMember(Value = "amortisedValue")]
            AmortisedValue = 3,

            /// <summary>
            /// Enum DigitalTokenUnit for digitalTokenUnit
            /// </summary>
            [EnumMember(Value = "digitalTokenUnit")]
            DigitalTokenUnit = 4
        }

        /// <summary>
        /// Specifies the type of the amount.
        /// </summary>
        /// <value>Specifies the type of the amount.</value>
        /// <example>unit</example>
        [Required]
        [DataMember(Name = "type", EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Signed decimal number.
        /// </summary>
        /// <value>Signed decimal number.</value>
        /// <example>12000</example>
        [Required]
        [DataMember(Name = "value", EmitDefaultValue = true)]
        public decimal Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Quantity {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Quantity)obj);
        }

        /// <summary>
        /// Returns true if Quantity instances are equal
        /// </summary>
        /// <param name="other">Instance of Quantity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Quantity other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Type == other.Type ||

                    Type.Equals(other.Type)
                ) &&
                (
                    Value == other.Value ||

                    Value.Equals(other.Value)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)

                hashCode = hashCode * 59 + Type.GetHashCode();

                hashCode = hashCode * 59 + Value.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(Quantity left, Quantity right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Quantity left, Quantity right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
